spring:
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/rezervo
        username: postgres
        platform: POSTGRESQL
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      hibernate:
         ddl-auto: none
      
        
