spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.devtools.restart.log-condition-evaluation-delta=false
rateForBook=5
rateAllowedToDelete=2
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.jackson.serialization.fail-on-empty-beans=false
quotes.api = https://opinionated-quotes-api.gigalixirapp.com/v1/quotes
